services:
  postgres:
    image: postgres:15-alpine
    container_name: solarwinds-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: solarwinds
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
      TZ: "UTC"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
      - ./backups:/backups
    networks:
      - solarwinds-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d solarwinds"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: PgAdmin for database management (development only)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: solarwinds-pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@solarwinds.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - solarwinds-network
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - dev
      - development

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  solarwinds-network:
    driver: bridge
    name: solarwinds-network