version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: solarwinds-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: solarwinds
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - solarwinds-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d solarwinds"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  solarwinds-network:
    driver: bridge